# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
