# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_part_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
