# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171108_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
