# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20171108_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='serial',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
