# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20171123_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerpart',
            name='part',
        ),
        migrations.RemoveField(
            model_name='workerpart',
            name='worker',
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='parttype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set([('part', 'serial')]),
        ),
        migrations.DeleteModel(
            name='WorkerPart',
        ),
    ]
