# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_worker_parts'),
        ('inventory', '0006_auto_20171205_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('part', models.ManyToManyField(blank=True, default=None, null=True, to='inventory.Part')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Worker')),
            ],
            options={
                'verbose_name': 'Детали в ригах',
                'verbose_name_plural': 'Детали в ригах',
            },
        ),
    ]
