# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('broken', models.BooleanField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Parts')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.PartsDetails')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Worker')),
            ],
        ),
    ]
