# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_parts_partsdetails_workersparts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsdetails',
            name='part',
        ),
        migrations.RemoveField(
            model_name='workersparts',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='workersparts',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.DeleteModel(
            name='PartsDetails',
        ),
        migrations.DeleteModel(
            name='WorkersParts',
        ),
    ]
