# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20171205_1439'),
        ('monitoring', '0003_auto_20171108_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='parts',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='inventory.Part'),
        ),
    ]
